### ISSUE TITLE
npm run dev 后 localhost:8080 白屏

### ISSUE THREAD

**Issue by eczn** [codecosine/ReliabilityPlatform#1]
白屏
chrome F12查看的时候 #app 里面是空的..

**Comment by eczn** [comment]
![image](https://cloud.githubusercontent.com/assets/13131724/20657167/c25470c6-b56e-11e6-8a6d-5fd074e9d9fa.png)
main.js报错了

**Comment by ycosine** [comment]
我特地自己又直接下载，试了一次，没有发现这个情况
试一下用cnpm install进行依赖安装
从报错情况是由于babel没有正常编译代码导致的。
